# Generated by Django 3.2 on 2021-04-21 22:08

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='html_content',
            field=django_quill.fields.QuillField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='key',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
