# Generated by Django 3.2 on 2021-04-21 22:13

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20210421_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='html_content',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='value',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
