# Generated by Django 3.2 on 2021-04-21 23:19

import album.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_category_document_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.FileField(default=None, upload_to=album.models.user_directory_path),
            preserve_default=False,
        ),
    ]
