# Generated by Django 3.2 on 2021-04-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_document_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='typology',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('pdf', 'PDF')], default='photo', max_length=16),
        ),
    ]
