# Generated by Django 3.2 on 2021-04-22 00:12

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0008_document_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.category'),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
