# Generated by Django 3.2 on 2021-04-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0009_auto_20210422_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
