# Generated by Django 3.2 on 2021-04-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0010_donor_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
